### PR TITLE
Merchant dashboard statistics

### PR DESCRIPTION
**Pull request by B-gann21**
Features: 
1. establish has_many relationships:
     - Merchant has many InvoiceItems, Invoices, Transactions, and Customers
     - Customer has many Transactions
2. create model method customer.successful_transactions (returns only successful transactions)
3. create model method merchant.customers_ordered_by_transactions (orders customers by number of successful transactions)
4. create model method merchant.top_five_customers (just grabs the first 5 from the top of the customers_ordered_by_transactions method)

Note: I have yet to figure out the active record method to do what i need for customers_ordered_by_transactions, so i went ahead and just used a Ruby sort_by loop. Could likely be refactored to use ActiveRecord once we learn more about aggregation.

### CODE REVIEW

**Comment by B-gann21** [comment]
Refactor: Was able to replace the raw Ruby code with ActiveRecord. It's not as pretty or readable, but we are expected to have no Ruby being used to process data

**Comment by amsalmeron** [comment]
Brylan you are a super star ⭐️

**Comment by Eagerlearn** [comment]
Reviewed new AR code for top 5 customers based on transactions and the tests. Will merge and clone down repo.

**Comment by CLRM1** [comment]
Great update, query is super easy to read.

**Pull request merged**
