### PR TITLE
Top 5 merchants

### PR DESCRIPTION
**Pull request by B-gann21**
- Creates class method Merchant.top_five which returns the 5 best merchants based on total revenue

### CODE REVIEW

**Comment by B-gann21** [comment]
Note that i had created a total_revenue instance method but had to delete it because total_revenue is already created in the top_five method

**Comment by CLRM1** [comment]
All tests passing, looks good to merge.

**Comment by amsalmeron** [comment]
Green light from me.

Way to get those tests passing consistently. What was the fix?

**Comment by Eagerlearn** [comment]
* Good call on using a class method for top 5 merchants in merchant model
* Test data is very clean and thorough (also nice shout out to include all 4 of us as merchants :) )
* Very effective use of within blocks
* I like the way you condensed test using the "relationships, attributes, instance methods" syntax (I like that idea and will see if I have opportunities to use it in any of my remaining stories)

**Comment by Eagerlearn** [comment]
All members have reviewed branch and approve the merge.

**Pull request merged**
