### PR TITLE
Admin dashboard links

### PR DESCRIPTION
**Pull request by CLRM1**
Features:

- Adds links to the admin merchants and admin invoices index pages in the admin/index view.
- Adds test for each link.

### CODE REVIEW

**Comment by B-gann21** [comment]
Looks pretty good, both this PR and Craig's PR have the same Controller and views being made - I think we should merge Craig's first and then this one 👌 but the code is well written and the tests are thorough. Good work!

**Comment by amsalmeron** [comment]
I like it. No complaints from me.

**Comment by Eagerlearn** [comment]
* I agree with the prior comments and will work with Chris to resolve the conflicts and merge the branch

**Comment by Eagerlearn** [comment]
Conflicts resolved to remove 'whitespace'.  Will merge

**Pull request merged**
