### PR TITLE
Rake tasks

### PR DESCRIPTION
**Pull request by B-gann21**
Features:
- Add migrations and schema for all classes
- Build models and relationships for all classes 

RakeTasks: 
- Add individual 'csv_load:' task for each class
- Add 'csv_load:all' task which does it all at once

Note: Had to edit the transaction.csv file b/c the empty column 'credit_card_expiration_date' was causing errors

### CODE REVIEW

**Comment by Eagerlearn** [comment]
Craig:
* Great job with the relationships as well as the overall code to load the CSV files and build out the models!
* Nice use of enums to the transactions status
* What are you thoughts on adding validates_numericality_of for the fields containing integers like unit_cost, CC#...etc
* Good catch on re-adding the FK to Items for Merchants
* Was there a problem with the Time.parse that caused you to remove it?

**Comment by B-gann21** [comment]
I think validating numericality is a great idea - will get that done once Antonio and Chris are done reviewing tomorrow! 

As for the Time.parse, it seemed to be working fine so I had it in all of the tests. The created_at and updated_at columns in all of the tables are datetime columns, so using Time.parse when generating the actual object is not necessary

**Comment by B-gann21** [comment]
Numericality is all validated - i also made sure to check that the database can still be loaded after the new validations. Still works 👍

**Comment by amsalmeron** [comment]
Looks great! The csv_load rake file looks very well built. Really enjoy the #create_from_csv to call any requested task. Tests are well built, good job.

The use of enum feels like it will come in handy throughout the project. I would like to review how to incorporate these as well as the validating numerically function. This is the first time I have encountered these methods. 

Only addition I can think of is to add /coverage to our .gitignore relieving simplecov from our git tracker.

**Comment by B-gann21** [comment]
Good idea with the .gitignore file - will do!

As per  Reviewing the new methods, feel free to message me on slack this afternoon if you would like to meet up. I am free all afternoon after 1 PM

**Comment by CLRM1** [comment]
Well done! The model tests are robust and well structured.  The rake file is easy to read. I went through each task and did some spot checking to compare the CSV data with the DB and everything looked great. The only suggestion I have would be to put a link to our schema from dbdiagram in the README.

**Comment by CLRM1** [comment]
Closed for refactor.

**Pull request closed without merging**
